### ISSUE TITLE
Beets Verbose Errors

### ISSUE THREAD

**Issue by undaunt** [MxMarx/lidarr-beets#2]
I enabled beets verbose mode as I was trying to enable copying instead of hard linking the files after processing and I saw we aren't specifying the plugin path within the config.yml. I'm also seeing the following errors repeatedly and was wondering if they were of concern:

Edit: Are we leveraging a beets contained within Lidarr and not requiring a separate container? I may have misunderstood that part when I had put the scripts with my existing beets database and mounted it to /beets. If a separate beets container is not required, this may not be of concern and can likely be closed.

Thanks!

```
06/27/2023 10:43:37 AM
user configuration: /config/config.yaml
06/27/2023 10:43:37 AM
data directory: /config
06/27/2023 10:43:37 AM
plugin paths: 
06/27/2023 10:43:38 AM
** error loading plugin originquery:
06/27/2023 10:43:38 AM
Traceback (most recent call last):
06/27/2023 10:43:38 AM
  File "/usr/lib/python3.10/site-packages/beets/plugins.py", line 268, in load_plugins
06/27/2023 10:43:38 AM
    namespace = __import__(modname, None, None)
06/27/2023 10:43:38 AM
ModuleNotFoundError: No module named 'beetsplug.originquery'
06/27/2023 10:43:38 AM
06/27/2023 10:43:38 AM
lyrics: Disabling google source: no API key configured.
06/27/2023 10:43:38 AM
ImageMagick version check failed: [Errno 2] No such file or directory: 'magick'
06/27/2023 10:43:38 AM
ImageMagick version check failed: [Errno 2] No such file or directory: 'convert'
06/27/2023 10:43:38 AM
artresizer: method is (1, (0,))
06/27/2023 10:43:38 AM
embedart: ImageMagick 6.8.7 or higher not installed; 'compare_threshold' option ignored
06/27/2023 10:43:38 AM
Sending event: pluginload
06/27/2023 10:43:38 AM
library database: /config/library.db
06/27/2023 10:43:38 AM
library directory: /music
06/27/2023 10:43:38 AM
Sending event: library_opened
06/27/2023 10:43:38 AM
error: unknown command 'web'
```

My compose file:

```
# Lidarr - Music Automated Acquisition
  lidarr:
    image: lscr.io/linuxserver/lidarr:develop
    container_name: lidarr
    <<: *common-apps
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $DOCKERDIR/beets:/beets
      - $MEDIADIR:/mnt/media
    environment:
      <<: *default-env
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PIP_PACKAGES: git+https://github.com/beetbox/beets.git|git+https://github.com/MxMarx/gazelle-origin@orpheus|git+https://github.com/MxMarx/beets-originquery|pyacoustid|beetcamp|pylast|python3-discogs-client 
      INSTALL_PACKAGES: git|ffmpeg|flac|imagemagick
      API_KEY_RED: xxxxxxxx
      API_KEY_OPS: xxxxxxxx
    labels:
      - traefik.enable=true
      ## HTTP Routers Auth Bypass
      - traefik.http.routers.lidarr-bypass.entrypoints=https
      - traefik.http.routers.lidarr-bypass.rule=Host(`lidarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$LIDARR_API_KEY`) || Query(`apikey`, `$LIDARR_API_KEY`))
      - traefik.http.routers.lidarr-bypass.priority=20
      ## HTTP Routers
      - traefik.http.routers.lidarr.entrypoints=https
      - traefik.http.routers.lidarr.rule=Host(`lidarr.$DOMAINNAME`)
      - traefik.http.routers.lidarr.priority=10
      ## Middlewares
      - traefik.http.routers.lidarr.middlewares=chain-authelia@file
      - traefik.http.routers.lidarr-bypass.middlewares=chain-no-auth@file
      ## HTTP Services
      - traefik.http.routers.lidarr.service=lidarr
      - traefik.http.routers.lidarr-bypass.service=lidarr
      - traefik.http.services.lidarr.loadbalancer.server.port=8686

# Beets - Music Tagging/Organization
  beets:
    image: lscr.io/linuxserver/beets
    container_name: beets
    <<: *common-apps
    volumes:
      - $DOCKERDIR/beets:/config
      - $MEDIADIR/music:/music
    environment:
      <<: *default-env
```
